### ISSUE TITLE
dataloader quesstion

### ISSUE THREAD

**Issue by zhu011** [floatingstarZ/GeRSP#1]
Hello dear author, thank you for your work, I have some questions about your work, first of all, about your dataset gersp.py the data types are imagenet and imgfloder, this is defined there. Also, if I want to define a new ex_data, what are the requirements, such as image size, or can I enter any image?

**Comment by floatingstarZ** [comment]
For ImageNet, you can use any labeled classification dataset. For ImageFolder, any image data can be used. There are no specific requirements for image size since they will be resized to a common size during training. However, since we are employing image contrastive learning, it is recommended that the images are relevant to classification tasks and only contain a few objects.

**Comment by zhu011** [comment]
After your answer, I arranged the imagenet dataset as a data_source, the data format is test directory for all images (no subfolders), anno is a txt file but will report an error like Traceback (most recent call last):
File "/home/zmj/zyf/GeRSP-main/tools/train.py", line 203,in module>
maino
File "/home/zmj/zyf/GeRSP-main/mmselfsup/datasets/builder.py"， line 43，in build_datasetdataset = build_from_cfg(cfg,DATASETS,default_args)
File "/nome/zoj/anaconda3/envs/gensp/lib/python3.9/site-packages/mcv/utils/negistry.py"，line 72，in build_from_cf9raise type(e)(f'{obj_cls.__name__}: {e}')
ValueErroP: MultiViewDACPDataset: ImageNet: not enough values to unpack (expected 2， got 1)

**Comment by floatingstarZ** [comment]
The ImageNet dataset should have subdirectories for proper reading, where each subdirectory represents a category.
